nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AARS_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AARS.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AATF_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AATF.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ACI_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ACI.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AGGF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AGGF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AGO2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AGO2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AKAP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AKAP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AKAP8L_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AKAP8L.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ALKBH1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ALKBH1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ALKBH5_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ALKBH5.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ALYREF_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ALYREF.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/APOBEC3C_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/APOBEC3C.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/AQR_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/AQR.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ATXN2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ATXN2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/BCLAF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/BCLAF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/BUD13_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/BUD13.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CAPRIN1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CAPRIN1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CDC40_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CDC40.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CELF2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CELF2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CHTOP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CHTOP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CNBP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CNBP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPEB4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPEB4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF6_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF6.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CPSF7_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CPSF7.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CSTF2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CSTF2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/CSTF2T_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/CSTF2T.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX24_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX24.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX3X_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX3X.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX51_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX51.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX55_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX55.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX59_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX59.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DDX6_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DDX6.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DGCR8_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DGCR8.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DHX30_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DHX30.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DICER1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DICER1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DIS3L2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DIS3L2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DKC1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DKC1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/DROSHA_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/DROSHA.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EFTUD2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EFTUD2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF3A_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF3A.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF3B_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF3B.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF3D_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF3D.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF3G_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF3G.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF3H_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF3H.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF4A3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF4A3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EIF4G2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EIF4G2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ELAVL1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ELAVL1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/EWSR1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/EWSR1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FAM120A_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FAM120A.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FASTKD2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FASTKD2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FBL_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FBL.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FIP1L1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FIP1L1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FMR1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FMR1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FTO_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FTO.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FUBP3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FUBP3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FUS_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FUS.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FXR1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FXR1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/FXR2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/FXR2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/G3BP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/G3BP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/GEMIN5_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/GEMIN5.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/GPKOW_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/GPKOW.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/GRSF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/GRSF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/GRWD1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/GRWD1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/GTF2F1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/GTF2F1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HLTF_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HLTF.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPA1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPA1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPC_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPC.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPD_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPD.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPF_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPF.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPH_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPH.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPK_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPK.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPL_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPL.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPM_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPM.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/HNRNPU_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/HNRNPU.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/IGF2BP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/IGF2BP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/IGF2BP2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/IGF2BP2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/IGF2BP3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/IGF2BP3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ILF3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ILF3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/KHSRP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/KHSRP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/LARP4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/LARP4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/LARP7_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/LARP7.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/LIN28A_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/LIN28A.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/LIN28B_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/LIN28B.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/LSM11_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/LSM11.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/MATR3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/MATR3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/MBNL2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/MBNL2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/METAP2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/METAP2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/METTL14_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/METTL14.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/METTL3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/METTL3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/MKRN1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/MKRN1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/MOV10_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/MOV10.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/MTPAP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/MTPAP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NCBP2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NCBP2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NCBP3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NCBP3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NIP7_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NIP7.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NIPBL_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NIPBL.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NKRF_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NKRF.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NOL12_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NOL12.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NOLC1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NOLC1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NONO_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NONO.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NOP58_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NOP58.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NUDT21_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NUDT21.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/NXF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/NXF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PABPC4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PABPC4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PABPN1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PABPN1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PCBP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PCBP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PCBP2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PCBP2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PHF6_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PHF6.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PPIG_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PPIG.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PPIL4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PPIL4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PRPF4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PRPF4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PRPF8_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PRPF8.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PTBP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PTBP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PUM1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PUM1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/PUM2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/PUM2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/QKI_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/QKI.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBFOX1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBFOX1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBFOX2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBFOX2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBM10_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBM10.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBM15_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBM15.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBM15B_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBM15B.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBM22_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBM22.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBM47_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBM47.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RBPMS_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RBPMS.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RPS3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RPS3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/RTCB_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/RTCB.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SAFB_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SAFB.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SAFB2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SAFB2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SDAD1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SDAD1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SDOS_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SDOS.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SERBP1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SERBP1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SF3A3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SF3A3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SF3B1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SF3B1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SF3B4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SF3B4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SLTM_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SLTM.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SMN_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SMN.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SMNDC1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SMNDC1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SND1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SND1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRRM4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRRM4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRSF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRSF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRSF10_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRSF10.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRSF3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRSF3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRSF7_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRSF7.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SRSF9_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SRSF9.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SSB_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SSB.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/STAU1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/STAU1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SUB1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SUB1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/SUPV3L1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/SUPV3L1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TAF15_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TAF15.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TARDBP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TARDBP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TBRG4_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TBRG4.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TDP43_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TDP43.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TIA1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TIA1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TIAL1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TIAL1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TRA2A_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TRA2A.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/TROVE2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/TROVE2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/U2AF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/U2AF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/U2AF2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/U2AF2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/U2AF65_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/U2AF65.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/UCHL5_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/UCHL5.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/UNR_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/UNR.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/UPF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/UPF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/UTP18_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/UTP18.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/UTP3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/UTP3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/WDR33_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/WDR33.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/WDR43_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/WDR43.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/WRN_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/WRN.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/WTAP_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/WTAP.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/XPO5_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/XPO5.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/XRCC6_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/XRCC6.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/XRN2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/XRN2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YBX3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YBX3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YTHDC1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YTHDC1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YTHDC2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YTHDC2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YTHDF1_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YTHDF1.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YTHDF2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YTHDF2.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/YTHDF3_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/YTHDF3.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ZC3H11A_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ZC3H11A.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ZC3H7B_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ZC3H7B.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ZNF622_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ZNF622.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ZNF800_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ZNF800.txt &
nohup cat /data1/MuSIC2_new_model/MotifLearnModel/Fig_data/Fig6/cutoff_0.9_rna_name/ZRANB2_* > /home/bioinfo/02_project/05_RBP/05_homo/bed/ZRANB2.txt &
