nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_aa &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ab &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ac &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ad &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ae &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_af &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ag &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ah &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ai &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_aj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ak &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_al &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_am &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_an &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ao &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ap &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_aq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ar &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_as &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_at &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_au &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_av &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_aw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ax &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ay &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_az &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ba &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_be &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bf &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bi &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bk &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bo &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_br &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bs &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bt &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bu &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bv &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bx &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_by &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_bz &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ca &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ce &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cf &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ch &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ci &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ck &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_co &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cr &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cs &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ct &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cu &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cv &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cx &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cy &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_cz &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_da &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_db &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_de &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_df &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_di &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dk &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_do &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dr &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ds &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dt &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_du &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dv &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dx &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dy &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_dz &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ea &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ec &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ed &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ee &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ef &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ei &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ej &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ek &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_el &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_em &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_en &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eo &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ep &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_er &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_es &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_et &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_eu &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ev &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ew &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ex &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ey &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ez &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fa &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fe &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ff &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fi &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fk &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fo &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fr &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fs &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ft &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fu &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fv &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fx &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fy &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_fz &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ga &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ge &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gf &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gi &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gk &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_go &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gr &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gs &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gt &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gu &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gv &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gw &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gx &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gy &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_gz &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ha &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hb &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hc &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hd &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_he &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hf &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hg &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hh &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hi &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hj &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hk &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hl &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hm &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hn &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_ho &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hp &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hq &
nohup bash /home/bioinfo/02_project/05_RBP/05_homo/script/update_bed_snk/update_bed_hr &
